version: '3.9'
networks:
  proxy:
    external: true
  internal:
    external: true
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    networks:
      - proxy
